"""Minimal per-k LBK screen.

This is a deliberately small implementation of the algebraic boundary-kernel
screen used in the paper.  It is not a full inflationary trajectory or Boltzmann
calculation.  For each wavenumber k it builds a hidden-sector kernel from the
canonical moduli masses, forms the Schur complement, normalizes at the Planck
pivot, and returns a primordial scalar spectrum.
"""
import os
import csv
import numpy as np
import matplotlib.pyplot as plt

OUT = "figures"
os.makedirs(OUT, exist_ok=True)

# Planck 2018 primordial scalar fit used for a first screen.
A_s = 2.10e-9
sigma_lnA = 0.014
n_s = 0.9649
sigma_ns = 0.0042
k_star = 0.05  # Mpc^{-1}

# Benchmark canonical mass eigenvalues from the full G^{-1} H screen.
MODELS = {
    r"$(3,3)$": np.array([122.6, 255.6]),
    r"$(1,5)$": np.array([34.1, 72.1]),
    r"$S^3\times S^3$": np.array([12.1, 30.3]),
}

# Dimensionless demonstration parameters.
# H2 sets the units of the benchmark Hessian masses; b is the mixing vector
# between the curvature perturbation and hidden canonical modes.
H2 = 10.0
b = np.array([0.40, 0.22])

def planck_power(k):
    return A_s * (k / k_star) ** (n_s - 1.0)

def planck_envelope(k):
    p1 = np.exp(np.log(A_s) - sigma_lnA) * (k / k_star) ** ((n_s - sigma_ns) - 1.0)
    p2 = np.exp(np.log(A_s) + sigma_lnA) * (k / k_star) ** ((n_s + sigma_ns) - 1.0)
    return np.minimum(p1, p2), np.maximum(p1, p2)

def schur_response(k, masses2, H2=H2, b=b):
    """Dimensionless response P_zeta/P_zeta,0 at one k.

    Minimal algebraic kernel:
        K_eff = K_zeta zeta - b^T K_HH^{-1} b,
        K_HH = diag(mu_a^2 + x^2), x=k/k_*, mu_a^2=m_a^2/H^2.
    The corresponding scalar covariance is proportional to 1/K_eff.
    """
    x = k / k_star
    mu2 = np.asarray(masses2, dtype=float) / H2
    hidden_diag = mu2 + x * x
    schur = np.sum((b[:len(mu2)] ** 2) / hidden_diag)
    return 1.0 / (1.0 - schur)

def primordial_curve(k_grid, masses2):
    # Normalize to the measured amplitude at the pivot, so the screen tests shape.
    R = np.array([schur_response(k, masses2) for k in k_grid])
    R_star = schur_response(k_star, masses2)
    return planck_power(k_grid) * R / R_star

def main():
    k = np.logspace(-4, np.log10(0.2), 600)
    baseline = planck_power(k)
    lower, upper = planck_envelope(k)

    rows = []
    curves = {}
    for name, masses2 in MODELS.items():
        P = primordial_curve(k, masses2)
        curves[name] = P
        inside = np.logical_and(P >= lower, P <= upper)
        rms_fractional = float(np.sqrt(np.mean(((P - baseline) / baseline) ** 2)))
        rows.append({
            "model": name.replace("$", ""),
            "inside_percent": 100.0 * float(np.mean(inside)),
            "rms_fractional_residual": rms_fractional,
            "P_at_pivot": float(np.interp(k_star, k, P)),
        })

    with open("minimal_per_k_kernel_results.csv", "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=rows[0].keys())
        writer.writeheader()
        writer.writerows(rows)

    with open("minimal_per_k_kernel_values.tex", "w") as f:
        f.write("% Automatically generated by minimal_per_k_kernel.py\n")
        f.write(r"\newcommand{\PerKThirtyThreeInside}{%.1f}\n" % rows[0]["inside_percent"])
        f.write(r"\newcommand{\PerKOneFiveInside}{%.1f}\n" % rows[1]["inside_percent"])
        f.write(r"\newcommand{\PerKSthreeInside}{%.1f}\n" % rows[2]["inside_percent"])
        f.write(r"\newcommand{\PerKThirtyThreeRMS}{%.3f}\n" % rows[0]["rms_fractional_residual"])
        f.write(r"\newcommand{\PerKOneFiveRMS}{%.3f}\n" % rows[1]["rms_fractional_residual"])
        f.write(r"\newcommand{\PerKSthreeRMS}{%.3f}\n" % rows[2]["rms_fractional_residual"])

    plt.rcParams.update({
        "font.size": 12, "axes.titlesize": 13, "axes.labelsize": 13,
        "legend.fontsize": 10, "xtick.labelsize": 11, "ytick.labelsize": 11,
        "mathtext.fontset": "cm",
    })

    fig, ax = plt.subplots(figsize=(7.0, 4.8), constrained_layout=True)
    rel_lower = lower / baseline - 1.0
    rel_upper = upper / baseline - 1.0
    ax.fill_between(k, 100 * rel_lower, 100 * rel_upper, alpha=0.22,
                    label=r"Planck 2018 $1\sigma$ parameter envelope")
    ax.axhline(0, lw=1.2, ls="--")
    for name, P in curves.items():
        ax.semilogx(k, 100 * (P / baseline - 1.0), lw=2.0, label=name)
    ax.axvline(k_star, ls=":", lw=1.2)
    ax.set_xlabel(r"$k\, [{\rm Mpc}^{-1}]$")
    ax.set_ylabel(r"residual from Planck power law [percent]")
    ax.set_title(r"Minimal per-$k$ LBK screen")
    ax.legend(frameon=False, loc="best")
    ax.margins(x=0.02)
    fig.savefig(f"{OUT}/per_k_minimal_screen.pdf", bbox_inches="tight")
    fig.savefig(f"{OUT}/per_k_minimal_screen.png", dpi=240, bbox_inches="tight")
    plt.close(fig)

    print(rows)

if __name__ == "__main__":
    main()
